version: '3.8'

services:
  gruasucabproviderms:
    image: gruasucabproviderms:latest
    build:
      context: .
      dockerfile: GruasUcabProviderMS/Dockerfile
    ports:
      - "5039:5039"
      - "7255:7255"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DBConnectionString=Host=labs-dbservices01.ucab.edu.ve;Database=GruasUcabProviderMS;Port=5432;Username=gmartinez;Password=123456;
      - ASPNETCORE_URLS=http://+:5039
    networks:
      - mynetwork
    command: >
      sh -c "dotnet ef database update --no-build && dotnet GruasUcabProviderMS.dll"


networks:
  mynetwork:
    driver: bridge
